export type DashboardLang = "en" | "es";

export const dashboardCopy = {
  en: {
    heroEyebrow: "PORTFOLIO-READY AI PRODUCT DEMO",
    heroTitle: "AI Portfolio Inbox & Insights",
    heroDescription:
      "A bilingual contact widget that analyzes inbound messages, groups them into smart threads, auto-replies in SQL-like structured summaries, and turns conversations into dashboard-ready product signals.",
    openWidget: "Open inbox widget",
    viewDashboard: "View dashboard",
    analysisTitle: "AI ANALYSIS",
    analysisDesc: "OpenAI configured",
    smtpTitle: "EMAIL OWNER INBOX",
    smtpDesc: "SMTP configured",
    gaTitle: "TRAFFIC INTELLIGENCE",
    gaDesc: "GA4 optional",
    widgetTitle: "Bilingual contact inbox",
    latestThreads: "Latest inbox threads",
    refresh: "Refresh",
    low: "Low",
    medium: "Medium",
    high: "High",
    question: "Question",
    projectInquiry: "Project inquiry",
    suggestion: "Suggestion",
    bugReport: "Bug report",
    generalFeedback: "General feedback",
    totalMessages: "Total messages",
    totalThreads: "Total threads",
    avgLeadScore: "Avg. lead score",
    languages: "Languages",
    messagesByPriority: "Messages by priority",
    messagesByCategory: "Messages by category",
    messagesByDay: "Messages by day",
    messageDetail: "Message detail",
    summary: "Summary",
    rawMessage: "Original message",
    suggestedReply: "Suggested reply",
    emailStatus: "Email status",
    language: "Language",
    priority: "Priority",
    category: "Category",
    createdAt: "Created at",
  },
  es: {
    heroEyebrow: "DEMO IA LISTA PARA PORTFOLIO",
    heroTitle: "Bandeja IA del Portfolio e Insights",
    heroDescription:
      "Un widget de contacto bilingüe que analiza mensajes entrantes, los agrupa en hilos inteligentes, genera resúmenes estructurados y convierte conversaciones en señales útiles para dashboard.",
    openWidget: "Abrir widget del inbox",
    viewDashboard: "Ver dashboard",
    analysisTitle: "ANÁLISIS IA",
    analysisDesc: "OpenAI configurado",
    smtpTitle: "EMAIL DEL PROPIETARIO",
    smtpDesc: "SMTP configurado",
    gaTitle: "INTELIGENCIA DE TRÁFICO",
    gaDesc: "GA4 opcional",
    widgetTitle: "Inbox de contacto bilingüe",
    latestThreads: "Últimos hilos del inbox",
    refresh: "Actualizar",
    low: "Baja",
    medium: "Media",
    high: "Alta",
    question: "Pregunta",
    projectInquiry: "Consulta de proyecto",
    suggestion: "Sugerencia",
    bugReport: "Error",
    generalFeedback: "Feedback general",
    totalMessages: "Mensajes totales",
    totalThreads: "Hilos totales",
    avgLeadScore: "Lead score medio",
    languages: "Idiomas",
    messagesByPriority: "Mensajes por prioridad",
    messagesByCategory: "Mensajes por categoría",
    messagesByDay: "Mensajes por día",
    messageDetail: "Detalle del mensaje",
    summary: "Resumen",
    rawMessage: "Mensaje original",
    suggestedReply: "Respuesta sugerida",
    emailStatus: "Estado del email",
    language: "Idioma",
    priority: "Prioridad",
    category: "Categoría",
    createdAt: "Fecha",
  },
} as const;